// <auto-generated />
using System;
using Entity_Ogrenci_Kurs_Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Ogrenci_Kurs_Project.Migrations
{
    [DbContext(typeof(OgrenciKursDbContext))]
    [Migration("20230906154957_AddTableAdmins")]
    partial class AddTableAdmins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminK_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"));

                    b.Property<DateTime>("AcilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DersAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgretmenID")
                        .HasColumnType("int");

                    b.HasKey("DersID");

                    b.HasIndex("OgretmenID");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Kurs", b =>
                {
                    b.Property<int>("KursID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursID"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KursAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgretmenID")
                        .HasColumnType("int");

                    b.HasKey("KursID");

                    b.HasIndex("OgretmenID");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OgrenciDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenciEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.OgrenciKurs", b =>
                {
                    b.Property<int>("OgrenciKursID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciKursID"));

                    b.Property<int>("KursID")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.HasKey("OgrenciKursID");

                    b.HasIndex("KursID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("Ogrenci_Kurslar");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Ogretmen", b =>
                {
                    b.Property<int>("OgretmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretmenID"));

                    b.Property<string>("OgretmenAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OgretmenDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgretmenEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgretmenSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgretmenID");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Ders", b =>
                {
                    b.HasOne("Entity_Ogrenci_Kurs_Project.Entities.Ogretmen", "Ogretmen")
                        .WithMany("Dersler")
                        .HasForeignKey("OgretmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Kurs", b =>
                {
                    b.HasOne("Entity_Ogrenci_Kurs_Project.Entities.Ogretmen", "Ogretmen")
                        .WithMany("Kurslar")
                        .HasForeignKey("OgretmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.OgrenciKurs", b =>
                {
                    b.HasOne("Entity_Ogrenci_Kurs_Project.Entities.Kurs", "Kurs")
                        .WithMany("OgrenciKurslar")
                        .HasForeignKey("KursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity_Ogrenci_Kurs_Project.Entities.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciKurslar")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Kurs", b =>
                {
                    b.Navigation("OgrenciKurslar");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Ogrenci", b =>
                {
                    b.Navigation("OgrenciKurslar");
                });

            modelBuilder.Entity("Entity_Ogrenci_Kurs_Project.Entities.Ogretmen", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Kurslar");
                });
#pragma warning restore 612, 618
        }
    }
}
